#!/bin/bash
RED='#400000'
BLUE='#000040'
GREEN='#004000'
PURPLE='#400040'
ORANGE='#804000'
GREY='#404040'

DAY=$(date '+%a')
HOUR=$(date '+%H')

_select_session_file() {
  if [[ "$KITTY_SESSION_FILE" != '' ]]; then
    echo "$KITTY_SESSION_FILE"
    return 0
  fi

  if [[ "$DAY" == 'Sat' || "$DAY" == 'Sun' || $(expr "$HOUR" '>=' 17) == 1 ]]; then
    echo "$HOME/.kitty/weekend.session"
    return 0
  fi

  echo "$HOME/.kitty/default.session"
}

SESSION_FILE=$(_select_session_file)


case "$1" in
  red)
    COL="$RED"
    ;;
  blue)
    COL="$BLUE"
    ;;
  green)
    COL="$GREEN"
    ;;
  purple)
    COL="$PURPLE"
    ;;
  orange)
    COL="$ORANGE"
    ;;
  grey)
    COL="$GREY"
    ;;
  random|'')
    COL=$(
      {
        echo "$BLUE"
        echo "$PURPLE"
        echo "$GREY"
      } | sort -R | head -n 1
    )
    ;;
  *)
    echo "Unsupported colour $1" >&2
    exit 1
    ;;
esac

nohup kitty --session "$SESSION_FILE" -o="background=$COL" & disown
