#!/bin/bash
RED='#400000'
BLUE='#000040'
GREEN='#004000'
PURPLE='#400040'
ORANGE='#804000'
GREY='#404040'

SESSION_FILE="${KITTY_SESSION_FILE:-$HOME/.kitty/default.session}"

case "$1" in
  red)
    COL="$RED"
    ;;
  blue)
    COL="$BLUE"
    ;;
  green)
    COL="$GREEN"
    ;;
  purple)
    COL="$PURPLE"
    ;;
  orange)
    COL="$ORANGE"
    ;;
  grey)
    COL="$GREY"
    ;;
  random|'')
    COL=$(
      {
        echo "$BLUE"
        echo "$PURPLE"
        echo "$GREY"
      } | sort -R | head -n 1
    )
    ;;
  *)
    echo "Unsupported colour $1" >&2
    exit 1
    ;;
esac

nohup kitty --session "$SESSION_FILE" -o="background=$COL" & disown
