#!/bin/bash

git ls-tree -r --name-only HEAD . | grep -i -E '\.(scala$|py|sh|sql|json|yaml|conf|feature|xml|md|mustache|js$)' |
  while read f; do
    git blame -w "$f"
  done |
  sed -E 's/^[a-f0-9]+ ([^ ]+ +)?\(([^ ]+).*$/\2/g' |
  sort |
  uniq -c |
  sort -rn

