#!/usr/bin/env python3

from random import SystemRandom
import string
import sys


def main():
    rng = SystemRandom()
    desired_len = int(sys.argv[1]) if len(sys.argv) > 1 else 64
    alphabet = string.ascii_letters + string.digits
    print(''.join([rng.choice(alphabet) for _ in range(desired_len)]))


if __name__ == '__main__':
    main()
