#!/bin/bash

FILE=${1:-/dev/stdin}
ENVIRON=$(echo $(hostname) | sed -E 's/\..+$//')

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
GREY=$(tput setaf 8)

GREENISH=$(tput setaf 36)
BLUEISH=$(tput setaf 39)
PINKISH=$(tput setaf 176)
PALE_YELLOW=$(tput setaf 230)

UNDERLINE=$(tput smul)

RESET=$(tput sgr0)

### PATTERN FRAGMENTS

TS='[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}'
TS_MS='[\.,][0-9]{3}'
TS_TZ='\+[0-9]{4}'
TS_FULL="($TS)($TS_MS)?($TS_TZ)?"

# This one matches a character which might separate certain IDs from their surroundings
TERM_DELIM='[^a-zA-Z0-9]|$'

HTTP_METHODS='GET|POST|DELETE|PUT|OPTIONS'
HTTP_SUCCESS_CODES='200|201|202'
HTTP_FAIL_CODES='400|401|403|418|500|502|503'
HTTP_WARN_CODES='404'

URL='https?:\/\/[a-zA-Z0-9\-_/\.:]+'

CLASSPATH=' ([a-z]\.){2,}[a-zA-Z0-9_-]+'

UUID='[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
ORDER_REF='[0-9]{8,9}'
DOCID='[a-f0-9]{24}'

###

while read line; do
  echo "$line" | sed -E \
    -e "s/\s*\[?[a-zA-Z0-9\._-]*$ENVIRON[a-zA-Z0-9\._-]*\]?\s*//g" \
    -e 's/(, )?\[actor: [a-zA-Z0-9\.:\/_-]+\]*//g' \
    -e "s/[ -]{3,}/ - /g" \
    -e "s/ \|?(DEB|TRA)(UG|CE)\|? / $GREY\1$RESET /" \
    -e 's/ \|?(INF)O?\|? / \1 /' \
    -e "s/ \|?(WAR)N?(ING)?\|? / $YELLOW\1$RESET /" \
    -e "s/ \|?(ERR)(OR)?\|? / $RED\1$RESET /" \
    -e "s/$TS_FULL/$UNDERLINE\1\2$RESET/" \
    -e "s/($CLASSPATH)/$GREY\1$RESET/" \
    -e "s/($URL)/$PALE_YELLOW\1$RESET/g" \
    -e "s/($TERM_DELIM)($DOCID)($TERM_DELIM)/\1$GREENISH\2$RESET\3/g" \
    -e "s/($UUID)/$BLUEISH\1$RESET/g" \
    -e "s/($TERM_DELIM)($ORDER_REF)($TERM_DELIM)/\1$BLUEISH\2$RESET\3/g" \
    -e "s/ ($HTTP_METHODS) /$PINKISH \1 $RESET/g" \
    -e "s/ ($HTTP_SUCCESS_CODES) /$GREEN \1 $RESET/g" \
    -e "s/ ($HTTP_WARN_CODES) /$YELLOW \1 $RESET/g" \
    -e "s/ ($HTTP_FAIL_CODES) /$RED \1 $RESET/g"
done < $FILE
