#!/bin/bash

# Simple, pretty version of cloudwatch describe-alarms

GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
MAGENTA=$(tput setaf 13)
RESET=$(tput sgr0)

extract_alarms() {
  jq -r '.[] | map(.AlarmName + "|" + .AlarmDescription) | .[]'
}

present_row() {
  COL="$1"

  sed -E "s/^([^|]+)\|(.*$)$/$COL\1$RESET: \2/"
}

echo ''
echo 'ALARM:'
aws cloudwatch describe-alarms --state-value ALARM |
  extract_alarms |
  present_row "$MAGENTA" || exit 1


echo ''
echo 'INSUFFICIENT DATA:'
aws cloudwatch describe-alarms --state-value INSUFFICIENT_DATA |
  extract_alarms |
  present_row "$YELLOW" || exit 2

echo ''
echo 'OK:'
aws cloudwatch describe-alarms --state-value OK |
  extract_alarms |
  present_row "$GREEN" || exit 3
