#!/bin/bash

# Quickly grab a codebuild log using `awslogs`

PROJECT="$DEFAULT_CODEBUILD_PROJECT"
BUILD_ID=''

usage() {
  echo 'Usage: codebuild-log [-p PROJECT] BUILD_ID'
}

while [[ "$#" != 0 ]]; do
  case "$1" in
    --project|-p)
      shift
      PROJECT="$1"
      shift
      ;;
    -*)
      echo "Unrecognised flag $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [[ "$BUILD_ID" != '' ]]; then
        echo 'Too many arguments!' >&2
        usage >&2
        exit 1
      fi
      BUILD_ID="$1"
      shift
      ;;
  esac
done

if [[ "$PROJECT" == '' ]]; then
  echo 'No project specified; please provide the -p/--project option' >&2
  echo 'or else set the DEFAULT_CODEBUILD_PROJECT environment variable' >&2
  exit 2
fi

if [[ "$BUILD_ID" == '' ]]; then
  usage >&2
  exit 3
fi

awslogs get -s '1970-01-01 00:00:00' -G -S /aws/codebuild/$PROJECT $BUILD_ID
