#!/bin/bash

# Quickly grab a codebuild log using `awslogs`

PROJECT=''
BUILD_ID=''
EXTRA_FLAGS=''

YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

usage() {
  echo 'Usage: codebuild-log [-p PROJECT] BUILD_ID'
}

_info() {
  echo "$YELLOW$1$RESET"
}

while [[ "$#" != 0 ]]; do
  case "$1" in
    --project|-p)
      shift
      PROJECT="$1"
      shift
      ;;
    -w)
      EXTRA_FLAGS="$EXTRA_FLAGS -w"
      shift
      ;;
    -*)
      echo "Unrecognised flag $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [[ "$BUILD_ID" != '' ]]; then
        echo 'Too many arguments!' >&2
        usage >&2
        exit 1
      fi
      BUILD_ID="$1"
      shift
      ;;
  esac
done

if [[ "$PROJECT" == '' ]]; then
  PROJECT=$(
    aws codebuild list-projects |
      jq -r '.projects[]' |
      fzf --ansi -i -0 -1 +m --prompt='Select project: '
  )
  if [[ "$PROJECT" == '' ]]; then
    echo 'No project provided' >&2
    exit 2
  fi
fi

if [[ "$BUILD_ID" == '' ]]; then
  _info 'No build ID provided; trying latest...'
  BUILD_ID=$(
    aws codebuild list-builds-for-project --project-name "$PROJECT" |
      jq -r '.ids | .[0]' |
      cut -d ':' -f 2
  ) || exit 3
  _info "Using build $BUILD_ID"
fi

awslogs get $EXTRA_FLAGS \
  -s '1970-01-01 00:00:00' \
  -G -S \
  /aws/codebuild/$PROJECT $BUILD_ID
