#!/bin/bash

# Quickly find EC2 instance state by ID

POLL_FREQ=0
INSTANCE_ID=''

FIELD_STATE="\"state\": .Reservations[0].Instances[0].State,"
SELECTED_FIELDS='state'
FIELDS="$FIELD_STATE"

print_state() {
  aws ec2 describe-instances --instance-ids "$1" |
    jq -r "{$FIELDS}"
}

usage() {
  echo 'Usage: ec2-instance-state INSTANCE_ID [-p]'
  echo ''
  echo 'Options:'
  echo ''
  echo 'INSTANCE_ID         AWS instance ID to check state of'
  echo '-p, --poll FREQ     Poll every FREQ seconds until stopped, instead of'
  echo '                    executing once'
  echo '-s                  Print instance state (on by default)'
  echo '-S                  Do not print instance state'
}

while [[ "$#" != 0 ]]; do
  case "$1" in
    -p|--poll)
      shift
      POLL_FREQ="$1"
      shift
      ;;
    -*)
      echo "Unknown flag $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [[ "$INSTANCE_ID" != '' ]]; then
        usage >&2
        exit 2
      fi

      INSTANCE_ID="$1"
      shift
      ;;
  esac
done

if [[ "$INSTANCE_ID" == '' ]]; then
  echo 'Instance ID is required' >&2
  usage >&2
  exit 3
fi

if [[ "$POLL_FREQ" != 0 ]]; then
  while true; do
    print_state "$INSTANCE_ID"
    sleep "$POLL_FREQ"
  done
else
  print_state "$INSTANCE_ID"
fi
