#!/bin/bash

cd $(dirname $0)
TMP=$(mktemp /tmp/ec2-connect.XXXXXXXX)
IP_PATTERN='(?:[0-9]{1,3}\.){3}[0-9]{1,3}'

if ! which fzf &> /dev/null; then
  echo 'Please install fzf to use this script'
  exit 1
fi

./find-ec2 "$1" | grep -E "$IP_PATTERN" | fzf -i -0 -1 +m --prompt='Select host: '
