version: '3'

services:
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"

  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    depends_on:
      - elasticsearch
