# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Python
export WORKON_HOME=~/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

# JS / node
export NPM_PACKAGES="$HOME/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
export PATH="$PATH:$NPM_PACKAGES/bin"

# Elephant mode
export HISTSIZE=100000
export HISTFILESIZE=
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# This suppresses spurious warnings from gtk applications about failure to register
# with an accessibility bus
export NO_AT_BRIDGE=1

# Docker stuff
export DOCKER_URL='unix:///var/run/docker.sock'

# Extra PS1 marker if in a nix shell, for clarity
_nix_marker() {
#  local _marker='🐚'
  local _marker='*'
  if [[ "$_USE_NIX_MARKER" == 1 ]]; then
    echo -n "$_marker"
    return
  fi

  if echo "$PATH" | grep -F '/nix/store' &> /dev/null; then
    export _USE_NIX_MARKER=1
    echo -n "$_marker"
  fi
}

export PS1='$(_nix_marker)${PS1_MARKER}'"\W \[$(tput setaf 1)\]\$(__git_ps1 '(%s) ')\[$(tput setaf 3)\]\[$(tput bold)\]\\$ \[$(tput sgr0)\]"

PATH="$PATH:/usr/local/go/bin:/usr/local/heroku/bin:$HOME/.pokemon-terminal"
PATH="$PATH:/opt/blackbox/bin"
PATH="$PATH:/opt/spark/bin:$HOME/.jenv/bin"
PATH="$PATH:/opt/mc/bin"
export PATH="$PATH:/opt/coursier/bin:$HOME/.local/share/coursier/bin"

# Tell fzf to use ag so that it ignores .gitignore stuff
export FZF_DEFAULT_COMMAND='ag --hidden -g ""'

# Always use gvim
alias vim=gvim

# Docked redis-cli for ease
alias redis-cli='docker run --net host --rm -it --entrypoint redis-cli redis'

# Useful aliases / definitions
alias purge_swap="find . -name '*.swp' -delete"

alias tmux='tmux -2'

export NIX_SHELL_PRESERVE_PROMPT=1

# TMUX SHORTCUTS

# Wrap a command in a tmux session if not already in one
_in_tmux() {
  if [[ "$TMUX" != '' ]]; then
    $(tmux $*)
    return
  fi

  SESSION_NAME=auto-tmux-$RANDOM
  tmux new -d -s $SESSION_NAME -c $(pwd)
  $(tmux $* -t $SESSION_NAME )
  tmux attach -t $SESSION_NAME
}

dps() {
  $HOME/scripts/dps "$@"
}

dsbt() {
  /opt/docker-sbt/wrapper.sh "$@"
}

cdl() {
  $HOME/scripts/format/cdl "$@"
}

logs() {
  "$HOME/scripts/aws/logs" "$@"
}

# Kitty icat
icat() {
  kitty +kitten icat "$@"
}

ecr() {
  if [[ "$AWS_ECR_ACCOUNT" == '' ]]; then
    echo 'You need to set $AWS_ECR_ACCOUNT in your environment to use this shortcut.' >&2
    echo 'This should be in a format like <account_id>.dkr.ecr.<region>.amazonaws.com' >&2
    return 1
  fi
  aws ecr get-login-password | docker login --username AWS --password-stdin "$AWS_ECR_ACCOUNT"
}

dcr() {
  local SERVICE="$1"
  docker-compose stop "$SERVICE" && docker-compose rm -f "$SERVICE" && docker-compose up -d "$SERVICE"
}

# Amm options to work with different libraries
amm() {
  /opt/ammonite/bin/amm "$@"
}
amm-cats() {
  amm -p "$HOME/.ammonite/predef_cats.sc" "$@"
}
amm-zio() {
  amm -p "$HOME/.ammonite/predef_zio.sc" "$@"
}
amm-spark() {
  amm -p "$HOME/.ammonite/predef_spark.sc" --class-based "$@"
}

alias vsplit='_in_tmux split -h'
alias hsplit='_in_tmux split -v'

alias qf="$HOME/scripts/quickfind"
alias ubuntu='docker run --rm -it -w /mnt -v $(pwd):/mnt ubuntu:latest /bin/bash'
alias mp='mplayer -geometry 0%:100%'

# Vim modes
alias vim-ocean='vim -c "color oceandeep"'
alias vim-midnight='vim -c "color midnight"'
alias vim-log='vim -c "color oceandeep" -c "AnsiEsc"'
alias viml=vim-log
alias vim-json='vim -c "set filetype=json"'

## OS-SPECIFIC ALIASES

if [[ ! -d /Library ]]; then
  # Linux-specific aliases
  unalias ls &> /dev/null
  unalias which &> /dev/null
  alias ls='ls --color=auto'
  alias which='(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot'

  alias open=xdg-open
fi

unalias grep &> /dev/null
alias grep='grep --color=auto'
alias notes='vim -c RecentNotes'

# Alias these to the docker scripts only if it's not installed
if ! which ffmpeg &> /dev/null; then
  alias ffmpeg="$HOME/scripts/video/ffmpeg"
  alias ffprobe="$HOME/scripts/video/ffprobe"
fi

# Ensure symlinked dirs expand with trailing slash in autocomplete
bind 'set mark-symlinked-directories on'

export TERM=xterm-256color

# Shortcuts to some very useful scripts
ec2() {
  ~/scripts/aws/find_ec2.py "$@"
}

conn() {
  ~/scripts/aws/ec2_connect.py "$@"
}

jira() {
  if [[ "$JIRA_SUBDOMAIN" == '' ]]; then
    echo 'Set the $JIRA_SUBDOMAIN in ~/.work' >&2
    return 1
  fi

  CARD="${1:-$(git rev-parse --abbrev-ref HEAD)}"
  if ! echo "$CARD" | grep -E '^[A-Z]{1,6}\-[0-9]{1,8}$' &> /dev/null; then
    echo "$CARD doesn't look like a ticket number" >&2
    return 1
  fi

  open "https://$JIRA_SUBDOMAIN.atlassian.net/browse/$CARD"
}

eval "$(jenv init -)"
complete -C /usr/bin/terraform terraform

# Import other useful files
{
  . ~/.env
  . ~/.passwords
  . ~/.prettify
  . ~/.bashrc_venv
  . ~/.work
  . ~/.aliases
  . ~/.cargo/env
  . ~/.nix-profile/etc/profile.d/nix.sh
} &> /dev/null
