services:
  backend:
    image: giftig/go:latest
    volumes:
      - ${GO_REDIRECT_DATA_DIR}:/usr/src/db:z

  frontend:
    image: giftig/go-static:latest
    ports:
      - 80:80
    depends_on:
      - backend
