version: "3.9"
services:
  mongo:
    image: mongo:4.4.6
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ams
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command:
      [
        "--noauth",
        "--replSet",
        "rs0",
        "--port",
        "27017",
        "--bind_ip_all",
      ]
    logging:
      driver: none
